### ISSUE TITLE
can someone help me with texture compression

### ISSUE THREAD

**Issue by Manoa1911** [dhewm/dhewm3#447]
```
void idImage::UploadPrecompressedImage( byte *data, int len ) {
	ddsFileHeader_t	*header = (ddsFileHeader_t *)(data + 4);
	glewInit();
	// ( not byte swapping dwReserved1 dwReserved2 )
	header->dwSize = LittleLong( header->dwSize );
	header->dwFlags = LittleLong( header->dwFlags );
	header->dwHeight = LittleLong( header->dwHeight );
	header->dwWidth = LittleLong( header->dwWidth );
	header->dwPitchOrLinearSize = LittleLong( header->dwPitchOrLinearSize );
	header->dwDepth = LittleLong( header->dwDepth );
	header->dwMipMapCount = LittleLong( header->dwMipMapCount );
	header->dwCaps1 = LittleLong( header->dwCaps1 );
	header->dwCaps2 = LittleLong( header->dwCaps2 );

	header->ddspf.dwSize = LittleLong( header->ddspf.dwSize );
	header->ddspf.dwFlags = LittleLong( header->ddspf.dwFlags );
	header->ddspf.dwFourCC = LittleLong( header->ddspf.dwFourCC );
	header->ddspf.dwRGBBitCount = LittleLong( header->ddspf.dwRGBBitCount );
	header->ddspf.dwRBitMask = LittleLong( header->ddspf.dwRBitMask );
	header->ddspf.dwGBitMask = LittleLong( header->ddspf.dwGBitMask );
	header->ddspf.dwBBitMask = LittleLong( header->ddspf.dwBBitMask );
	header->ddspf.dwABitMask = LittleLong( header->ddspf.dwABitMask );

	// generate the texture number
	qglGenTextures( 1, &texnum );

	int externalFormat = 0;

	precompressedFile = true;

	uploadWidth = header->dwWidth;
	uploadHeight = header->dwHeight;
	unsigned short int bc7 = sizeof(ddsFileHeader_t);
	if ( header->ddspf.dwFlags & DDSF_FOURCC ) {
        switch ( header->ddspf.dwFourCC ) {
        case DDS_MAKEFOURCC( 'D', 'X', 'T', '1' ):
			if ( header->ddspf.dwFlags & DDSF_ALPHAPIXELS ) {
				internalFormat = GL_COMPRESSED_RGBA_S3TC_DXT1_EXT;
			} else {
				internalFormat = GL_COMPRESSED_RGB_S3TC_DXT1_EXT;
			}
			break;
        case DDS_MAKEFOURCC( 'D', 'X', 'T', '3' ):
            internalFormat = GL_COMPRESSED_RGBA_S3TC_DXT3_EXT;
			break;
        case DDS_MAKEFOURCC( 'D', 'X', 'T', '5' ):
            internalFormat = GL_COMPRESSED_RGBA_S3TC_DXT5_EXT;
			break;
		case DDS_MAKEFOURCC( 'R', 'X', 'G', 'B' ):
			internalFormat = GL_COMPRESSED_RGBA_S3TC_DXT5_EXT;
			break;
		case DDS_MAKEFOURCC( 'D', 'X', '1', '0' ):
			internalFormat = GL_COMPRESSED_RGBA_BPTC_UNORM;
			bc7 = bc7 + 20;
			uploadWidth = 256;
			uploadHeight = 1024;
			break;
        default:
            common->Warning( "Invalid compressed internal format\n" );
            return;
        }
    } else if ( ( header->ddspf.dwFlags & DDSF_RGBA ) && header->ddspf.dwRGBBitCount == 32 ) {
		externalFormat = GL_BGRA_EXT;
		internalFormat = GL_RGBA8;
    } else if ( ( header->ddspf.dwFlags & DDSF_RGB ) && header->ddspf.dwRGBBitCount == 32 ) {
        externalFormat = GL_BGRA_EXT;
		internalFormat = GL_RGBA8;
    } else if ( ( header->ddspf.dwFlags & DDSF_RGB ) && header->ddspf.dwRGBBitCount == 24 ) {
		if ( header->ddspf.dwFlags & DDSF_ID_INDEXCOLOR ) { 
			externalFormat = GL_COLOR_INDEX;
			internalFormat = GL_COLOR_INDEX8_EXT;
		} else {
			externalFormat = GL_BGR_EXT;
			internalFormat = GL_RGB8;
		}
	} else if ( header->ddspf.dwRGBBitCount == 8 ) {
		externalFormat = GL_ALPHA;
		internalFormat = GL_ALPHA8;
	} else {
		common->Warning( "Invalid uncompressed internal format\n" );
		return;
	}

	// we need the monochrome flag for the NV20 optimized path
	if ( header->dwFlags & DDSF_ID_MONOCHROME ) {
		isMonochrome = true;
	}

	type = TT_2D;			// FIXME: we may want to support pre-compressed cube maps in the future

	Bind();

	int numMipmaps = 1;
	if ( header->dwFlags & DDSF_MIPMAPCOUNT ) {
		numMipmaps = header->dwMipMapCount;
	}

	int uw = uploadWidth;
	int uh = uploadHeight;

	// We may skip some mip maps if we are downsizing
	int skipMip = 0;
	GetDownsize( uploadWidth, uploadHeight );

	byte *imagedata = data + bc7 + 4;

	for ( int i = 0 ; i < numMipmaps; i++ ) {
		int size = 0;
		if ( FormatIsDXT( internalFormat ) ) {
			size = ( ( uw + 3 ) / 4 ) * ( ( uh + 3 ) / 4 ) *
				(internalFormat <= GL_COMPRESSED_RGBA_S3TC_DXT1_EXT ? 8 : 16);
		} else {
			size = uw * uh * (header->ddspf.dwRGBBitCount / 8);
		}

		if ( uw > uploadWidth || uh > uploadHeight ) {
			skipMip++;
		} else {
			if ( internalFormat == GL_COMPRESSED_RGBA_BPTC_UNORM )
			{
 			 glCompressedTexImage2D( GL_TEXTURE_2D, 0, GL_COMPRESSED_RGBA_BPTC_UNORM, 256, 1024, 0, 256*1024, imagedata);
    GLenum err;
	err = glGetError();
common->Warning( getErrorString(err) );

			} else {
			if ( FormatIsDXT( internalFormat ) ) {
				glCompressedTexImage2D( GL_TEXTURE_2D, i - skipMip, internalFormat, uw, uh, 0, size, imagedata );
			} else {
				qglTexImage2D( GL_TEXTURE_2D, i - skipMip, internalFormat, uw, uh, 0, externalFormat, GL_UNSIGNED_BYTE, imagedata );
			}
			}
		}

		imagedata += size;
		uw /= 2;
		uh /= 2;
		if (uw < 1) {
			uw = 1;
		}
		if (uh < 1) {
			uh = 1;
		}
	}

	SetImageFilterAndRepeat();
}
```
I am trying to add BC7 to the original doom 3, this code compiles and runs correctly and shows GL_NO_ERROR, the texture is compressonator BC7, I have 2 of them with and without mipmaps. everything is good and all the non-BC7 render correctly, except the BC7 one which is rendering black :(
thank for help

**Comment by turol** [comment]
It was quite a while ago but I think BC7 requires a DX10 format DDS file and there's a whole separate extended header for it.

**Comment by Manoa1911** [comment]
![header](https://user-images.githubusercontent.com/73593192/157207031-a3cd3ba5-89ce-46b4-b35d-a2b67b3a0315.png)
is this good ?

**Comment by turol** [comment]
No idea, check ms documentation: https://docs.microsoft.com/en-us/windows/win32/direct3ddds/dds-header-dxt10

Or some library like GLI might support reading them.

**Comment by Manoa1911** [comment]
I managed to complete this implementation on the original doom 3, but in dhewm this doesn't work, I made all necessary changed to the code as I did with the original but they still appear black, I updated my SDL2 library and linked and included against it and I checked in it's files and the definitions for BC7 exist in there, but still the game does not show them, the format of the textures is correct as I have verified this with the original Doom 3 I modded, the function that loads the textures in dhewm is qglCompressedTexImage2DARB but in my code for Doom 3 that works with BC7 I used glCompressedTexImage2D, I have tried several variations to modify this function name but the result is undefined external symbols, when I do modify RenderSystemInit.cpp and add them above qgl_proc.h the engine crashes immediatly at load :(

**Comment by Manoa1911** [comment]
I fixed it :) it's working :)
how do I give you the patch ?

**Comment by DanielGibson** [comment]
Hi @Manoa1911 sorry I didn't look at this earlier and thanks a lot for the patch! :)

I implemented BC7 support based on this, see #661.
Could you test this? Could you give me a BC7 file from compressonator that doesn't load (also tell me what settings you used), in case this is still a problem? Then I'll try to debug that issue, maybe it's fixable :)
